default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitter_development
  username: postgres
  password: root
  host: localhost
  port: 5432

test:
  <<: *default
  database: twitter_test
  username: postgres
  password: root

production:
  <<: *default
  database: twitter_production
  username: postgres
  password: <%= ENV['TWITTER_DATABASE_PASSWORD'] %>
